name: Minecraft Plugin Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin-build
        path: build/libs/

    - name: Deploy to GitHub Packages
      uses: docker://ghcr.io/marketplace-actions/github-package-publish:latest
      with:
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}
        tag: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        packages: "jar=build/libs/*.jar"
